"use strict";

/**
 * Server component manifest.
 *
 * `required: true` marks the spine the process cannot serve without: accounts,
 * static shell, system health, settings and the provider/model registry.
 * Everything else is a feature surface that must be prunable.
 *
 * `routePrefixes` lets a pruned component answer its own routes with an
 * explicit "not installed" 503 instead of silently falling through to 404.
 */
const SERVER_COMPONENT_MANIFEST = Object.freeze([
  Object.freeze({
    id: "provider-telemetry-service",
    label: "Provider 遥测与健康服务",
    version: "2026.09.24",
    kind: "service",
    priority: 5,
    required: true,
  }),
  Object.freeze({
    id: "provider-bootstrap-service",
    label: "Provider 启动与迁移服务",
    version: "2026.09.24",
    kind: "service",
    priority: 6,
    dependencies: ["provider-telemetry-service"],
    required: true,
  }),
  Object.freeze({
    id: "provider-catalog-service",
    label: "Provider 模型目录服务",
    version: "2026.09.24",
    kind: "service",
    priority: 7,
    dependencies: ["provider-telemetry-service", "provider-bootstrap-service", "image-model-catalog"],
    required: true,
  }),
  Object.freeze({
    id: "static-http-api",
    label: "静态资源与输出文件 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 8,
    required: true,
    routePrefixes: ["/api/"],
  }),
  Object.freeze({
    id: "system-http-api",
    label: "系统健康与备份 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 10,
    required: true,
    routePrefixes: ["/api/system/", "/api/admin/backup"],
  }),
  Object.freeze({
    id: "auth-http-api",
    label: "认证与账户 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 12,
    required: true,
    routePrefixes: ["/api/auth/", "/api/admin/users", "/api/users/directory"],
  }),
  Object.freeze({
    id: "preferences-http-api",
    label: "账户偏好 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 14,
    required: true,
    routePrefixes: ["/api/preferences", "/api/settings"],
  }),
  Object.freeze({
    id: "provider-catalog-http-api",
    label: "Provider 模型目录 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 16,
    dependencies: ["provider-catalog-service"],
    required: false,
    routePrefixes: ["/api/models", "/api/image-models", "/api/video-models", "/api/vision-models"],
  }),
  Object.freeze({
    id: "provider-http-api",
    label: "Provider HTTP API",
    version: "2026.09.23",
    kind: "http-api",
    priority: 20,
    required: false,
    routePrefixes: ["/api/providers", "/api/protocols", "/api/jimeng-cli/"],
  }),
  Object.freeze({
    id: "comfyui-http-api",
    label: "ComfyUI HTTP API",
    version: "2026.09.23",
    kind: "http-api",
    priority: 30,
    required: false,
    routePrefixes: ["/api/comfyui/"],
  }),
  Object.freeze({
    id: "skill-http-api",
    label: "Skill HTTP API",
    version: "2026.09.23",
    kind: "http-api",
    priority: 35,
    required: false,
    routePrefixes: ["/api/skills", "/api/canvas-agent/skills"],
  }),
  Object.freeze({
    id: "background-removal-http-api",
    label: "后台抠图 HTTP API",
    version: "2026.09.23",
    kind: "http-api",
    priority: 40,
    required: false,
    routePrefixes: ["/api/background-removal"],
  }),
  Object.freeze({
    id: "image-model-catalog",
    label: "图片模型规则与目录",
    version: "2026.09.24",
    kind: "service",
    priority: 42,
    required: true,
  }),
  Object.freeze({
    id: "image-generation-http-api",
    label: "图片生成 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 43,
    dependencies: ["image-model-catalog"],
    required: false,
    routePrefixes: ["/api/images"],
  }),
  Object.freeze({
    id: "media-generation-http-api",
    label: "媒体生成 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 44,
    required: false,
    routePrefixes: [
      "/api/upscale",
      "/api/upscale2",
      "/api/videos",
      "/api/outpaint",
      "/api/runninghub-outpaint",
      "/api/shoe-swap",
      "/api/flux2-klein-edit",
      "/api/qwen-edit-angle",
      "/api/comfy-remove-background",
      "/api/minimax-h3-video",
    ],
  }),
  Object.freeze({
    id: "online-http-api",
    label: "在线状态 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 46,
    required: false,
    routePrefixes: ["/api/online"],
  }),
  Object.freeze({
    id: "resource-http-api",
    label: "资源与共享 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 45,
    required: false,
    routePrefixes: ["/api/resources", "/api/shares/"],
  }),
  Object.freeze({
    id: "media-http-api",
    label: "媒体上传 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 47,
    required: false,
    routePrefixes: ["/api/upload-image", "/api/upload-media"],
  }),
  Object.freeze({
    id: "image-sync-http-api",
    label: "图片本地化 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 48,
    required: false,
    routePrefixes: ["/api/image-sync/"],
  }),
  Object.freeze({
    id: "image-job-http-api",
    label: "图片任务 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 49,
    required: false,
    routePrefixes: ["/api/image-jobs"],
  }),
  Object.freeze({
    id: "asset-library-http-api",
    label: "素材库 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 50,
    required: false,
    routePrefixes: ["/api/assets"],
  }),
  Object.freeze({
    id: "canvas-project-http-api",
    label: "画布项目 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 55,
    required: false,
    routePrefixes: ["/api/canvas/projects"],
  }),
  Object.freeze({
    id: "canvas-storage-http-api",
    label: "画布存储 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 60,
    required: false,
    routePrefixes: ["/api/canvas/boards", "/api/canvas/import"],
  }),
  Object.freeze({
    id: "canvas-agent-http-api",
    label: "Canvas Agent HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 65,
    required: false,
    routePrefixes: ["/api/canvas-agent/"],
  }),
  Object.freeze({
    id: "chat-message-service",
    label: "聊天消息服务",
    version: "2026.09.24",
    kind: "service",
    priority: 66,
    required: true,
  }),
  Object.freeze({
    id: "chat-http-api",
    label: "聊天 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 67,
    dependencies: ["chat-message-service"],
    required: false,
    routePrefixes: ["/api/chat"],
  }),
  Object.freeze({
    id: "history-http-api",
    label: "历史记录 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 68,
    required: false,
    routePrefixes: ["/api/history/"],
  }),
  Object.freeze({
    id: "thumbnail-http-api",
    label: "缩略图 HTTP API",
    version: "2026.09.24",
    kind: "http-api",
    priority: 70,
    required: false,
    routePrefixes: ["/api/image-thumbnails"],
  }),
]);

module.exports = { SERVER_COMPONENT_MANIFEST };
